# The name of connection profile
name: "Org1 Client"
version: "1.0"

# Client section is for NodeJS SDK. 
client:
  organization: org1 # The org that this app instance belong to
  # set connection timeouts for the peer and orderer for the client
  connection:
    timeout:
      peer:
        # the timeout in seconds to be used on requests to a peer,
        # for example 'sendTransactionProposal'
        endorser: 120
        # the timeout in seconds to be used by applications when waiting for an
        # event to occur. This time should be used in a javascript timer object
        # that will cancel the event registration with the event hub instance.
        eventHub: 60
        # the timeout in seconds to be used when setting up the connection
        # with the peer's event hub. If the peer does not acknowledge the
        # connection within the time, the application will be notified over the
        # error callback if provided.
        eventReg: 30
      # the timeout in seconds to be used on request to the orderer,
      # for example
      orderer: 30
  credentialStore: # KVS of Client instance
    path: "/tmp/hfc-kvs/org1"
    cryptoStore: # Cryptosuite store of Client instance
      path: "/tmp/hfc-cvs/org1"

# Optinal. But most app would have this so that channle objects can be constructed based on this section.
channels:
  baotestchannel: # name of channel
    orderers:
      - orderer1-org0
    peers:
      peer1-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1-org2:
        endorsingPeer: true
        chaincodeQuery: false
        ledgerQuery: true
        eventSource: false
    chaincodes:
      - food_supplychain:v0

organizations:
  org0:
    mspid: org0MSP
    certificateAuthorities:
      - rca-org0
    adminPrivateKey:
      path: configs/crypto-config/orgs/org0/admin/msp/keystore/a1f904d6039fbddd4d5ba80cb7b72f8e43258037f7e57c79c2daff0ee49a76e4_sk
    signedCert:
      path: configs/crypto-config/orgs/org0/admin/msp/signcerts/cert.pem
  org1:
    mspid: org1MSP
    peers:
      - peer1-org1
      - peer2-org1
    certificateAuthorities:
      - rca-org1
    adminPrivateKey:
      path: configs/crypto-config/orgs/org1/admin/msp/keystore/df705de619515330c8ec267803584ad1ebd58186e4708222185563f792498d0b_sk
    signedCert:
      path: configs/crypto-config/orgs/org1/admin/msp/signcerts/cert.pem
  org2:
    mspid: org2MSP
    peers:
      - peer1-org2
      - peer2-org2
    certificateAuthorities:
      - rca-org2
    adminPrivateKey:
      path: configs/crypto-config/orgs/org2/admin/msp/keystore/eb458dcbb81bee8ec70cd1dc68a15afb8e06570f9064bf309e1075c325e80e7f_sk
    signedCert:
      path: configs/crypto-config/orgs/org2/admin/msp/signcerts/cert.pem

orderers:
  orderer1-org0:
    url: grpcs://orderer1-org0:7050
    grpcOptions:
      ssl-target-name-override: orderer1-org0
      grpc-keepalive-timeout-ms: 3000
      grpc.keepalive_time_ms: 360000
      grpc-max-send-message-length: 10485760
      grpc-max-receive-message-length: 10485760
    tlsCACerts:
      path: configs/crypto-config/orderer/msp/tlscacerts/rca-org0-7054.pem

peers:
  peer1-org1:
    url: grpcs://peer1-org1:7051
    eventUrl: grpcs://peer1-org1:7053
    grpcOptions:
      ssl-target-name-override: peer1-org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/peer1-org1/msp/tlscacerts/rca-org1-7054.pem
  peer2-org1:
    url: grpcs://peer2-org1:7051
    eventUrl: grpcs://peer2-org1:7053
    grpcOptions:
      ssl-target-name-override: peer2-org1
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/peer2-org1/msp/tlscacerts/rca-org1-7054.pem
  peer1-org2:
    url: grpcs://peer1-org2:7051
    eventUrl: grpcs://peer1-org2:7053
    grpcOptions:
      ssl-target-name-override: peer1-org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/peer1-org2/msp/tlscacerts/rca-org2-7054.pem
  peer2-org2:
    url: grpcs://peer2-org2:7051
    eventUrl: grpcs://peer2-org2:7053
    grpcOptions:
      ssl-target-name-override: peer2-org2
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/peer2-org2/msp/tlscacerts/rca-org2-7054.pem

certificateAuthorities:
  rca-org0:
    url: https://rca-org0:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/org0-ca-cert.pem
    registrar:
      - enrollId: rca-org0-admin
        enrollSecret: rca-org0-adminpw
    caName: rca-org0
  rca-org1:
    url: https://rca-org1:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/org1-ca-cert.pem
    registrar:
      - enrollId: rca-org1-admin
        enrollSecret: rca-org1-adminpw
    caName: rca-org1
  rca-org2:
    url: https://rca-org2:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/org2-ca-cert.pem
    registrar:
      - enrollId: rca-org2-admin
        enrollSecret: rca-org2-adminpw
    caName: rca-org2
